@extends('layouts.admin', [
    'title' => "Ban {$user->username}"
])

@section('meta')
    <meta name="site-info" data-name="{{ config('site.name') }}">
@endsection

@section('js')
    <script>
        var siteInfo = {};

        $(() => {
            const siteInfoMeta = $('meta[name="site-info"]');
            siteInfo.name = siteInfoMeta.attr('data-name');

            const presetsArray = [
                'CREATED_TO_BREAK_RULES',
                'CREATED_TO_BREAK_RULES_HISTORY',
                'COIN_FARMING',
                'INAPPROPRIATE_LINKS'
            ];

            const presets = {
                CREATED_TO_BREAK_RULES: {
                    title: 'Created to Break Rules',
                    length: 'closed',
                    category: 'none',
                    note: `Do not sign up to ${siteInfo.name} with intent on breaking our rules.`
                },

                CREATED_TO_BREAK_RULES_HISTORY: {
                    title: 'Refusal to follow TOS + Ban History',
                    length: 'closed',
                    category: 'none',
                    note: `Do not sign up to ${siteInfo.name} with intent on breaking our rules. Because of your extensive ban history and refusal to follow our Terms of Service, your account has been terminated.`
                },

                COIN_FARMING: {
                    title: 'Coin Farming',
                    category: 'coin_farming',
                    note: 'Do not use currency generated by alternative accounts for your own gain.'
                },

                INAPPROPRIATE_LINKS: {
                    title: 'Inappropriate Links',
                    category: 'inappropriate_links',
                    note: 'Do not post inappropriate links.'
                }
            };

            presetsArray.forEach((preset) => $('#presets').append(`<button type="button" class="blue small w-100 mb-2" data-auto-fill="${preset}">${presets[preset].title}</button>`));

            $('[data-auto-fill]').click(function() {
                const preset = presets[$(this).attr('data-auto-fill')];
                var messages = [];

                $('#alert').empty().hide();

                if (typeof preset['note'] !== 'undefined')
                    $('textarea[name="note"]').val(preset['note']);
                else
                    messages.push('You still need to provide a note for this preset.');

                if (typeof preset['length'] !== 'undefined')
                    $('select[name="length"]').val(preset['length']);
                else
                    messages.push('You still need to provide a length for this preset.');

                if (typeof preset['category'] !== 'undefined')
                    $('select[name="category"]').val(preset['category']);
                else
                    messages.push('You still need to provide a category for this preset.');

                if (messages.length) {
                    var output = '';

                    messages.forEach((message) => output += `<div>${message}</div>`);

                    $('#alert').html(output).show();
                }
            });
        });
    </script>
@endsection

@section('content')
    <div class="alert bg-danger text-white" id="alert" style="display:none;"></div>
    <div class="row">
        <div class="col-md-7">
            <div class="card">
                <div class="card-header">Ban</div>
                <div class="card-body">
                    <form action="{{ route('admin.users.ban.create') }}" method="POST">
                        @csrf
                        <input type="hidden" name="id" value="{{ $user->id }}">

                        <span class="font-weight-bold d-block">User:</span>
                        <a class="d-block mb-2" href="{{ route('users.profile', $user->id) }}" target="_blank">{{ $user->username }}</a>

                        <span class="font-weight-bold d-block">Length:</span>
                        <select class="form-control mb-2" name="length" required>
                            @foreach ($lengths as $name => $value)
                                <option value="{{ $value }}">{{ $name }}</option>
                            @endforeach
                        </select>

                        <span class="font-weight-bold d-block">Category:</span>
                        <select class="form-control mb-2" name="category" required>
                            @foreach ($categories as $name => $value)
                                <option value="{{ $value }}">{{ $name }}</option>
                            @endforeach
                        </select>

                        <textarea class="form-control mb-2" name="note" style="height:100px;" placeholder="Note">{{ old('note') }}</textarea>
                        <textarea class="form-control mb-2" name="content" style="height:100px;" placeholder="Content (optional)">{{ old('content') }}</textarea>

                        <button type="submit" class="blue">SUBMIT</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">Auto Fill</div>
                <div class="card-body" id="presets"></div>
            </div>
        </div>
    </div>

    @if(isset($ban_history) && $ban_history->count() > 0)
        <div class="card">
            <div class="card-header">Ban history</div>
            <div class="card-body">
                <table class="table mb-0">
                    <tbody>
                        @foreach($ban_history as $ban)
                            <tr>
                                <td>
                                    @if($ban->banner)
                                        <a href="{{ route('users.profile', $ban->banner->id) }}" target="_blank">{{ $ban->banner->username }}</a>
                                    @else
                                        Unknown
                                    @endif
                                </td>
                                <td><b>{{ ucfirst(str_replace('_', ' ', $ban->category ?? 'none')) }}</b>: "<i>{{ $ban->note }}</i>" for <b>{{ ucfirst(str_replace('_', ' ', $ban->length)) }}</b> on {{ $ban->created_at }}</td>
                                <td>{{ ($ban->active) ? 'Active' : 'Expired' }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="pages">{{ $ban_history->onEachSide(1) }}</div>
            </div>
        </div>
    @endif
@endsection
